### ISSUE TITLE
Issue regrading LG ultrafine

### ISSUE THREAD

**Issue by yyl217** [jhelgert/hackintosh#1]
How does LG ultrafine will work with this motherboard?

**Comment by jhelgert** [comment]
To clarify, I don't use the original LG Ultrafine 27" 5K. Instead, it's the same display panel the Ultrafine uses, i.e. the LM270QQ2, but with [this](https://www.aliexpress.com/item/4000014899510.html?spm=a2g0o.productlist.0.0.784c7ecfSrKN1x&algo_pvid=6f374814-7570-42e6-a76c-f991f4a6e2c0&algo_expid=6f374814-7570-42e6-a76c-f991f4a6e2c0-1&btsid=0ab6f82c15918678021758733ee2b0&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) driver board. Then there's no Thunderbolt required. A GPU with two DP inputs is sufficient to run the panel with 5K@60Hz.
